### ISSUE TITLE
fatal: 'pyside2_global.h' file not found

### ISSUE THREAD

**Issue by nim65s** [ros-melodic-arch/ros-melodic-qt-gui-cpp#11] opened 2019-11-20 15:03 UTC
Hi,

This PKGBUILD still has references to python3.7.

After updating those, I get the following issue, even if pyside2 is installed:
```
[ 52%] Running SIP generator for qt_gui_cpp_sip Python bindings...
sip: Deprecation warning: qt_gui_cpp.sip:1: %Module version number should be specified using the 'version' argument
qt.shiboken: (typesystem) CLANG builtins includes directory: /usr/lib/clang/9.0.0/include
(typesystem) clang_parseTranslationUnit2(0x0, cmd[11]=-isystem/usr/lib/clang/9.0.0/include -fPIC -Wno-constant-logical-operand -std=c++14 -I/tmp/ros-melodic-qt-gui-cpp/src/qt_gui_core-0.3.14/qt_gui_cpp/include -I/usr/include/qt -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/lib/qt/mkspecs/linux-g++ /tmp/global_etwQDQ.hpp)
/tmp/ros-melodic-qt-gui-cpp/src/qt_gui_core-0.3.14/qt_gui_cpp/src/qt_gui_cpp_shiboken/global.h:37:10: fatal error: 'pyside2_global.h' file not found
(typesystem) Errors in /tmp/global_etwQDQ.hpp:
/tmp/ros-melodic-qt-gui-cpp/src/qt_gui_core-0.3.14/qt_gui_cpp/src/qt_gui_cpp_shiboken/global.h:37:10: fatal: 'pyside2_global.h' file not found
   /tmp/global_etwQDQ.hpp:1:10: note: in file included from /tmp/global_etwQDQ.hpp:1:


(typesystem) Clang: 1 diagnostic messages:
  /tmp/ros-melodic-qt-gui-cpp/src/qt_gui_core-0.3.14/qt_gui_cpp/src/qt_gui_cpp_shiboken/global.h:37:10: fatal: 'pyside2_global.h' file not found
   /tmp/global_etwQDQ.hpp:1:10: note: in file included from /tmp/global_etwQDQ.hpp:1:


Keeping temporary file: /tmp/global_etwQDQ.hpp
shiboken: Error running ApiExtractor.
Command line: --generatorSet=shiboken --include-paths=/tmp/ros-melodic-qt-gui-cpp/src/qt_gui_core-0.3.14/qt_gui_cpp/src/qt_gui_cpp_shiboken/../../include:/usr/include/qt/:/usr/include/qt/QtWidgets:/usr/include/qt/QtGui:/usr/include/qt/QtCore:/usr/lib/qt//mkspecs/linux-g++ --typesystem-paths=/usr/share/PySide2/typesystems --output-directory=/tmp/ros-melodic-qt-gui-cpp/src/build/src/qt_gui_cpp_shiboken global.h typesystem.xml
```

**Comment by nim65s** [comment] 2019-11-20 15:21
workaround found and tested here: https://github.com/ros-visualization/qt_gui_core/issues/142#issuecomment-445409573

**Comment by jwhendy** [comment] 2019-11-20 19:26
Re. python3.8, see [this issue](https://github.com/ros-melodic-arch/ros-melodic-desktop-full/issues/8). It appears (thanks to @acxz 's diging) that the 3.7 paths were just script-added unnecessarily to every one of these packages. That issue has the list of all the packages that *actually* depend on python paths. Just adding that comment, as the python3.7 observation was likely a false error.

Your output appears incomplete. I don't see the end of the failure itself, just an error about `ApiExtractor`.

Also, what was the specific workaround you found? That comment recommends installing `sip` and `python-sip`, but those are already [depends for this package](https://github.com/ros-melodic-arch/ros-melodic-qt-gui-cpp/blob/master/PKGBUILD#L33).

It's not clear what actually happened and what was the ultimate fix for you (that isn't handled here). Thanks for any additional details.

**Comment by nim65s** [comment] 2019-11-20 22:02
The workaround working for me was to remove the packages `pyside2` & `pyside2-tools` from my system.

I thought the error was about the `fatal error: 'pyside2_global.h' file not found`, appearing several  times, and the fact that the include path doesn't contains `/usr/share/PySide2`, which is where this `pyside2_global.h` is.

I can reproduce and  provide additional details if told how :)

**Comment by acxz** [comment] 2019-11-20 22:14
hmm, I will try to reproduce this when I get time later, but basically there might be an error when installing this package alongside `pyside2` & `pyside2-tools`? I also got an error recently when I had `shiboken2` installed, but didn't save the log. In any case I will try to reproduce.

**Comment by jwhendy** [comment] 2019-11-21 00:17
@nim65s Ah, that's helpful. So we could build fine not having those, but having them is causing some premature issue. I admit I have zero knowledge of this. You can see I was bitten by this over at that same linked bug. sip, shiboken, pyside... seems really weird that somehow each of these could individually satisfy whatever ROS wants.

@acxz I wonder if your `shiboken2` issue was related to [this](https://github.com/ros-melodic-arch/ros-melodic-python-qt-binding/pull/3)?

**Comment by acxz** [comment] 2020-01-13 15:55
I think so, but shiboken is now playing nice with me. Let me try to reproduce this issue with `pyside2` and `pyside2-tools`.

**Comment by acxz** [comment] 2020-01-13 16:04
Closing this issue, since it is a duplicate of https://github.com/ros-melodic-arch/ros-melodic-qt-gui-cpp/issues/12 and more convo has happened there.

**Closed as completed by acxz** 2020-01-13 16:04 UTC
